name: Backup Gitlab

on:
  push:
    tags:
      - "*"

jobs:
  backuptogitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup git
        run: |
          git config --global user.email "sostaric.borna@hotmail.com"
          git config --global user.name "Shoshta73"
          git remote set-url origin https://git:${GITLAB_TOKEN}@gitlab.com/Shoshta73/website.git

      - name: push
        run: |
          git push -f --follow-tags origin main
