name: Lint Check

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - run: pnpm run format:check
